# Docs-related PRs
documentation:
  - 'doc/**'
  - 'requirements-docs.txt'

# Source RST files
rst:
  - 'doc/source/**/*.rst'

# Config files
config:
  - '.github/**'
  - 'doc/Makefile'
  - 'doc/make.bat'
